---
# tasks file for oraclerestart 18c

- name: delete response file
  file:
    path: /home/oracle/grid.rsp
    state: absent

- name: check if ~oracle/.crsbuild exists
  stat:
    path: /home/oracle/.crsbuild
  register: crsbuild_present

- include_role:
    name: oracle.asm.disks
    public: yes
  when: crsbuild_present.stat.exists != True

- name: "ora_1_env file"
  template:
    src: ora_1_env.ASM
    dest: "/home/oracle/.ora_1_env"

- name: wait for oracle-ohasd.service
  systemd:
    name: oracle-ohasd.service
  register: oracle_ohasd_service

- debug:
    msg: "oracle-ohasd.service {{ oracle_ohasd_service.status.LoadState }}"

- name: check if Oracle CRS unpacked
  stat: 
    path: /oracle/u01/gi/{{ oracle_ver_path }}/bin/
  register: crs_unpacked
  
- debug:
    msg: "Install package exists: {{ crs_unpacked.stat.exists }}"

- name: Include Role oracle.download.package
  include_role:
    name: oracle.download.package
  vars:
    oracle_home: "/oracle/u01/gi/{{ oracle_ver_path }}"
  when: crs_unpacked.stat.exists != True and oracle_ohasd_service.status.LoadState == "not-found"

- name: check if Oracle CRS set up
  stat: 
    path: /oracle/u01/oraInventory/ContentsXML
  register: crs_set_up

- include: setup.grid.yml
  when: crs_set_up.stat.exists != True and oracle_ohasd_service.status.LoadState == "not-found"
  
- name: orainstRoot.sh
  shell: /oracle/u01/oraInventory/orainstRoot.sh
  args:
    creates: /etc/oraInst.loc

- name: root.sh   
  shell: /oracle/u01/gi/{{ oracle_ver_path }}/root.sh
  when: oracle_ohasd_service.status.LoadState == "not-found"

- name: wait for oracle-ohasd.service
  systemd:
    name: oracle-ohasd.service
    state: started
    enabled: yes
  register: oracle_ohasd_service

- debug:
    msg: "oracle-ohasd.service {{ oracle_ohasd_service.status.LoadState }}"

- name: Check asm configured
  command: "sh -c '/oracle/u01/gi/{{ oracle_ver_path }}/bin/crsctl status res ora.asm | grep ONLINE'"
  register: oracle_asm_status
  ignore_errors: true

- debug:
    msg: "{{ oracle_asm_status }}"

- name: "Execute Config Tools gridSetup.sh (part II)"
  block:
    - name: Grid Setup ASM
      shell: "./gridSetup.sh -executeConfigTools -responseFile /home/oracle/grid.rsp -silent"
      args:
        chdir: "/oracle/u01/gi/{{ oracle_ver_path }}"

  rescue:
    - name: delete response file
      file:
        path: /home/oracle/grid.rsp
        state: absent
    - fail:
        msg: '"./gridSetup.sh failed'

  become: yes
  become_user: oracle
  when: oracle_asm_status.stdout is not match(".*ONLINE")

- name: file perm fixup
  file:
    path: /oracle/u01/gi/{{ oracle_ver_path }}/bin/oracle
    owner: oracle
    group: oinstall
    mode: '6755'

- name: file perm fixup
  file:
    path: /oracle/u01/gi/{{ oracle_ver_path }}
    owner: root
    group: oinstall
    mode: '0755'

- name: file perm fixup
  file:
    path: /oracle/u01/gi/{{ oracle_ver_path }}/cdata/localhost/{{ansible_hostname}}.olr
    owner: oracle
    group: oinstall
    mode: '0600'

- name: Create ~oracle/.crsbuild
  block:
    - name: Create ~oracle/.crsbuild
      copy: content="{{ ansible_date_time.iso8601 }}" dest="/home/oracle/.crsbuild"
  become: yes
  become_user: oracle
  when: crsbuild_present.stat.exists != True
