---
# vars file for oraclerestart

oracle_major_version: "19"

# Note: there is dependecy between this and grid.rsp
# Base install package does not support
#  oracle.install.crs.configureGIMR=true
# While pathed Golden image does
#oracle_install_package_name: "linuxx64_12201_grid_home.zip"
oracle_install_package_names: ["LINUX.X64_193000_grid_home.zip"]

oracle_ver_path: "19.3.0.0"

asm_disks: []
asm_disk_partitions: []
